name: ontime
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # Core Firebase and Auth for Sprint 1 RBAC
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  image_picker: ^1.2.2
  firebase_storage: ^11.6.5
  intl: ^0.20.2
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  # Ensure indentation is exactly 2 spaces per level
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Ologo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android_12:
    image: assets/logoremake.png
    color: "#FFFFFF"