// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq2Q2_1ZCmT-xwJvuSq1w3ugGAfALv_8A',
    appId: '1:168959223360:web:1802173447c1ed107621a5',
    messagingSenderId: '168959223360',
    projectId: 'ontime-df19b',
    authDomain: 'ontime-df19b.firebaseapp.com',
    storageBucket: 'ontime-df19b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoMtmJTxzpY9uM-4y7Tc5ROglvXe-4_rs',
    appId: '1:168959223360:android:ce3293bbbf66af7d7621a5',
    messagingSenderId: '168959223360',
    projectId: 'ontime-df19b',
    storageBucket: 'ontime-df19b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUjOlzb9eeZEX0_DKneNQunDKTQzJZRGk',
    appId: '1:168959223360:ios:fa50ece23041def97621a5',
    messagingSenderId: '168959223360',
    projectId: 'ontime-df19b',
    storageBucket: 'ontime-df19b.firebasestorage.app',
    iosBundleId: 'com.example.ontime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUjOlzb9eeZEX0_DKneNQunDKTQzJZRGk',
    appId: '1:168959223360:ios:fa50ece23041def97621a5',
    messagingSenderId: '168959223360',
    projectId: 'ontime-df19b',
    storageBucket: 'ontime-df19b.firebasestorage.app',
    iosBundleId: 'com.example.ontime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq2Q2_1ZCmT-xwJvuSq1w3ugGAfALv_8A',
    appId: '1:168959223360:web:043df2cb2416402a7621a5',
    messagingSenderId: '168959223360',
    projectId: 'ontime-df19b',
    authDomain: 'ontime-df19b.firebaseapp.com',
    storageBucket: 'ontime-df19b.firebasestorage.app',
  );
}
