import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart';

// Import your separate UI files
import 'splash_screen.dart';
import 'get_started_screen.dart';
import 'welcome_and_login.dart';

void main() async {
  // Required to ensure Flutter is ready before calling Firebase
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with the options generated by FlutterFire CLI
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const OnTimeApp());
}

class OnTimeApp extends StatelessWidget {
  const OnTimeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'OnTime',
      debugShowCheckedModeBanner: false, // Removes the debug banner
      theme: ThemeData(
        // Matching your orange brand color from the Figma design
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.orange,
          primary: Colors.orange,
        ),
        useMaterial3: true,
      ),
      // The app starts with the Splash Screen
      home: const SplashScreen(),
    );
  }
}

/// The AuthGate acts as a "Router" that checks the user's login status.
/// You should navigate to this from your GetStartedScreen.
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // 1. Check if the user is NOT logged in
        if (!snapshot.hasData) {
          return const WelcomeLoginScreen(); // Your "Welcome & Login.png" UI
        }

        // 2. If logged in, the user proceeds to the dashboard.
        // NOTE: Later, you will add your RBAC logic here to check if
        // the user is an 'Employee' or 'Manager' in Firestore.
        return const MainDashboard();
      },
    );
  }
}

// --- Placeholder Screens to keep the app runnable ---
// Replace these with your actual UI files as you build them.

class MainDashboard extends StatelessWidget {
  const MainDashboard({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("OnTime Dashboard"),
        actions: [
          IconButton(
            icon: const Icon(Icons.logout),
            onPressed: () => FirebaseAuth.instance.signOut(),
          ),
        ],
      ),
      body: const Center(child: Text("Successfully Logged In!")),
    );
  }
}
